### ISSUE TITLE
Can we get an npm package for hjson?

### ISSUE THREAD

**Issue by AryanBeezadhur** [hjson/hjson#104]
I want to use hjson on the web in Node.js, and it would be possible and easy to do this if the project had a package on [npm](https://npmjs.com). Then we can install hjson to a project simply by using `npm install hjson`, for example.

Do the maintainers intend to introduce this?

Thanks

**Comment by dqsully** [comment]
We have an hjson package on NPM, see [here](https://www.npmjs.com/package/hjson).

**Comment by AryanBeezadhur** [comment]
Thanks! I didn't see that on the website

**Comment by trobro** [comment]
Says "Homepage: hjson.org" on the npm page, should be hjson.github.io.

**Comment by dqsully** [comment]
Nice catch. It should be fixed now
