### ISSUE TITLE
Mention deser-hjson as a solution for Rust

### ISSUE THREAD

**Issue by Canop** [hjson/hjson#108]
The old serde-hjson crate isn't compatible with the recent versions of serde, and isn't compatible with the usual and safe way to deserialize in Rust, which is to use [serde derive](https://serde.rs/derive.html).

For those reasons I wrote a new deserializer: https://crates.io/crates/deser-hjson

Having only the old one listed here prevents IMO the use of Hjson in Rust for many users.

So I propose to have deser-hjson listed too.

**Comment by trobro** [comment]
I don't use Rust myself, but this seems good, thanks for sharing! I'll add a link and mention in the top of our web page https://hjson.github.io/
