### ISSUE TITLE
check your syntax or use quotes if the key name includes {}[],: or whitespace

### ISSUE THREAD

**Issue by InterfaceBoy** [hjson/hjson#109]
Error: Found ',' where a key name was expected (check your syntax or use quotes if the key name includes {}[],: or whitespace) at line 1,153 >>>!DOCTYPE html><html  ...
    at h (hjson-parse.js:41)
    at y (hjson-parse.js:163)
    at C (hjson-parse.js:353)
    at T (hjson-parse.js:434)
    at Object.t.exports [as parse] (hjson-parse.js:454)

**Comment by trobro** [comment]
Please create an issue in the https://github.com/hjson/hjson-js repository instead, since that's the implementation you are using. Provide an example Hjson file that causes this error.
