### ISSUE TITLE
Error in ace syntax highlighting when key contains colon

### ISSUE THREAD

**Issue by stampyzfanz** [hjson/hjson#112]
When the key contains a colon in it, both sides of the key are highlighted orange because of their "keyword" classification. However, this conflicts with what the json states which is that the second half of the key is part of the value, and is given the string class.
Hjson: ![image](https://user-images.githubusercontent.com/34364128/148630602-7bab7687-52b0-4cd3-a24c-0f609d5c4626.png)
Json:  ![image](https://user-images.githubusercontent.com/34364128/148630613-0ae10747-f1b7-4113-9462-ac00d78d67d7.png)

**Comment by stampyzfanz** [comment]
I don't think I have permission to link to a pull request but I made one [here](https://github.com/hjson/hjson/pull/113)

**Comment by trobro** [comment]
Nice fix, thanks!
