### ISSUE TITLE
Ulong datatype wrong parse

### ISSUE THREAD

**Issue by Denny9700** [hjson/hjson#116]
I have a problem with the parsing of ulong / long datatypes. The end of the number isn't correct.
Now i upload some images that represent the problem. I hope can be fixed soon.

**Watch1 View**
![Image](https://user-images.githubusercontent.com/17761029/159239785-bd2776ef-a627-4acc-a1af-4704b4bcc3cd.PNG)

**HJson File**
![Image](https://user-images.githubusercontent.com/17761029/159239865-80463108-0c35-472a-b6fd-8fd2ca3672eb.PNG)

**The Class**
![Image](https://user-images.githubusercontent.com/17761029/159239877-4251afad-157b-416a-9251-68893aad4779.PNG)

**Comment by theAkito** [comment]
How did you solve this?

**Comment by Denny9700** [comment]
> How did you solve this?

I haven't fixed this problem, it's just the wrong place where discuss this error. I haven't seen the C# repo of this project before.
Anyway, maybe i clone this repo and fix this error by myself.
