### ISSUE TITLE
Comment delimiter choice

### ISSUE THREAD

**Issue by broofa** [hjson/hjson#12]
Drive-by comment here:  Why not use "//" for the comment delimiter?

'//' is JS-compatible, whereas '#' isn't.  It's odd that you would choose a JS-incompatible syntax for this when 1) there's no compelling advantage and 2) one of the design goals of the syntax you're forking is to remain JS-compatible.

**Comment by laktak** [comment]
`//` comments are now supported as well as `#` comments. This makes it possible to use Hjson as a replacement for config files that already use JSON + `//` comments.

**Comment by howardroark** [comment]
Hey @laktak ... If you supported `/*...*/` as well this could be an excellent drop in replacement for json5... https://github.com/aseemk/json5

Just a thought!

**Comment by laktak** [comment]
done, I think we now cover all comment styles ;)

**Comment by howardroark** [comment]
**old fashioned** I like it ;)
