### ISSUE TITLE
Definition of quoteless strings is oversimplified

### ISSUE THREAD

**Issue by cousteaulecommandant** [hjson/hjson#127]
I am reading the definition of quoteless strings at https://hjson.github.io/syntax.html and it seems incomplete.  According to the syntax diagrams and textual description, *anything* starting with a character other than `{}[],:` would qualify as a quoteless string.
I understand that the actual definition is more along the lines of "anything starting with a character other than `{}[],:` or whitespace *that cannot be interpreted as anything else*", is that correct?

Currently, the following are ambiguous and could be interpreted as a quoteless string or not; some examples may clarify:
* `x: #FF0000` - looks like a comment, but it starts with a character other than `{}[],:` so technically it could be a quoteless string too?
* `x: 5 #comment` - same here, this could be either `5` followed by a comment or the quoteless string `"5 #comment"` (I assume it'd be the former)
* `5 seconds #comment` - in this case I suspect that, since `5 seconds` can only be a quoteless string, then ` #comment` must also be part of it?
* `+10 #c`, `010 #c`, `0x10 #c`, `.99 #c` - these are tricky because they do look a lot like numbers (especially `010`) but I understand they are not, so in this case the ` #c` would be part of them?
* `5#comment` - finally this.  I assume that it's a `5` followed by a comment, and that comments work like in JS or Perl and need no whitespace before them, not as in POSIX shell where they'd be "part of a word" in this case.

I understand that my assumptions are correct, but it'd be nice if the specification document clarified this (and perhaps provided some examples).

**Comment by trobro** [comment]
There are some examples near the end of the syntax definitions page, and also mentioning of that anything that can be interpreted as some other type of value will not be interpreted as a quoteless string:

https://github.com/hjson/hjson/blob/6f94dd067ce59d43e4cc3d8eeaf932e5f627348a/pages/syntax.md?plain=1#L58

I can add some more examples there.

**Comment by cousteaulecommandant** [comment]
The documentation doesn't say that.  Only that "The Hjson parser will still detect values [...] and parse them correctly", which is a bit vague; it doesn't explicitly say that "*anything* that can be interpreted as [something else] will not be interpreted as a quoteless string".

It may be a good idea to mention it explicitly, and perhaps point out that a quoteless string cannot start with a comment-starting sequence (but may contain it).

Suggestions:

> A quoteless string cannot start with any of the punctuators (`{}[],:"'`) or a start of comment sequence (`#`, `//`, `/*`).

> The Hjson parser will only parse data as a quoteless string if any other interpretation fails, and therefore it will still detect values [...]

> * `1 block, 2 blocks # ah-ah-ah!` is the *string* [...]

**Comment by trobro** [comment]
PR #128 created with proposed changes.

**Comment by trobro** [comment]
Fixed
