### ISSUE TITLE
json2hsjon plus hjson2json in sublime - automatically 

### ISSUE THREAD

**Issue by ReSearchITEng** [hjson/hjson#34]
Hi,
 as 99% of the applications require json, it would be great to be able to have these done automatically when we open a json in sublime:
- have it automatically transformed in hjson 
  ->>> here humans do the editing
- at save, it should save back in json

I think this would be a great start to make hjson popular :)

**Comment by laktak** [comment]
Great idea! Are you interested in doing a PR for https://github.com/laktak/sublime-hjson? ;)

I wouldn't do it automatically though because if the user adds comments they would just disappear.

**Comment by mathiasrw** [comment]
>  99% of the applications require json

Lets all help informing/asking for hjson support.

**Comment by laktak** [comment]
@mathiasrw good idea!

There is also a tool called hed that makes it easy to edit json files with Hjson in any editor. See https://github.com/laktak/hed
