### ISSUE TITLE
Write an Augeas "lens" for hjson

### ISSUE THREAD

**Issue by TomOnTime** [hjson/hjson#41]
If augeas can grok hjson, then you have a way to parse and update hjson files without losing comments.  It also makes it easier for Puppet and other systems to automatically update hjson files.

http://augeas.net/

**Comment by laktak** [comment]
Looks like a great project, haven't heard of it before.

Do you have any experience writing a schema/lens?

**Comment by TomOnTime** [comment]
I've written some simple lens but I'm not very good at it.  There's one for json already (https://github.com/hercules-team/augeas/blob/master/lenses/json.aug).  I find that the authors are very helpful if you get stuck.

**Comment by laktak** [comment]
Well, I opened an issue, see https://github.com/hercules-team/augeas/issues/365. Not sure if it's possible.

**Comment by laktak** [comment]
Also see https://twitter.com/raphink/status/722910061685710848

**Comment by laktak** [comment]
The [SABNF](https://github.com/ldthomas/apg-js2/blob/master/SABNF.md) grammar can now be found [here](https://github.com/laktak/hjson/tree/master/rfc) if anyone likes to give it a try.
