### ISSUE TITLE
Failure to handle infinity and NaN limits hjson's usefulness.

### ISSUE THREAD

**Issue by JamesGosling** [hjson/hjson#54]
This line in section 7 of the RFC draft:

> Numeric values that cannot be represented in the grammar below (such as Infinity and NaN) are not permitted.

renders hjson much less useful than it could have been.  There are literals for true, false and null.  Why not +inf, -inf and NaN?  I've been looking forward to the wider adoption of hjson, to counter the rigidity of the json.org "standard", but for those of us who do math, this omission is a killer.

**Comment by laktak** [comment]
Please take a look at Domain Specific Formats.

**Comment by laktak** [comment]
I haven't updated the RFC yet but there is support for this in the Java, JavaScript and C# implementations.

For Java you can enable it like this:

```
HjsonOptions opt=new HjsonOptions();
opt.setDsfProviders(new IHjsonDsfProvider[] { HjsonDsf.math() });

JsonValue value=JsonValue.readHjson(reader, opt);
out.println(value.toString(opt));
```

Please let me know if this works as intended.

**Comment by laktak** [comment]
Closing as there is no response.
