### ISSUE TITLE
Strings with leading commas inside arrays are stringified without quotes

### ISSUE THREAD

**Issue by latonv** [hjson/hjson#55]
If a string within an array starts with one or more commas, stringifying with hjson-js incorrectly produces a Quoteless-String rather than a JSON-String. I've only seen this with hjson-js 2.0.4, and can't attest for implementations in other languages.

### Small example:

Javascript:
```javascript
arr = ["a", ",b"]; // Note the comma before the b
hjson.stringify(arr);
```

HJSON output:
```
[
  a
  ,b
]
```

Parsing the above output:
```javascript
arr = hjson.parse("[\n  a\n  ,b\n]"); // ["a", "b"] -- we lost our comma!
```

**Comment by laktak** [comment]
Thanks for the bug report and the sample! The bug is present in all implementations. I've added tests and [published a fix for js](https://github.com/hjson/hjson-js/commit/79510745c4567302d75dd45ab5f65b9a25c48667).
