### ISSUE TITLE
Array in array

### ISSUE THREAD

**Issue by mathiasrw** [hjson/hjson#57]
Not really sure if this goes here or in hjson-js - but:

On https://hjson.org/try.html I get the error 

````
Error: Syntax error, found trailing characters at line 2,5 >>>    [sales, max]
    ...
````

whey trying to parse the hjson

```hjson
config: [
    [sales, max]
    avg
]
```

I would expect it to output 

```json
{
  "config": [
    [
      "sales",
      "max"
    ],
    "avg"
  ]
}
```

**Comment by laktak** [comment]
Note that for quoteless strings everything up to the next line is part of the string (see http://hjson.org/syntax.html#quoteless-strings)

The input

```
config: [
    [sales, max]
    avg
]
```

is equivalent to the following (with quotes):

```
config: [
    ["sales, max]"
    "avg"
]
```

This is similar to the one you reported in #59 and will now also show the updated error message:

> Error: End of input while parsing an array (did you forget a closing ']'?)

Thanks for your feedback and finding a bug!
