### ISSUE TITLE
Single setting

### ISSUE THREAD

**Issue by mathiasrw** [hjson/hjson#58]
Does this goes on hjson-js repo or here?

When parsing the hjson On https://hjson.org/try.html

```
config: [max]
``` 

I would expect to get a json like

```json
{"config":["max"]}
```

but I get 

```
"config: [max]"
```

(and this is not valid json btw)

Bonus info: If I replcae `max` with a number the output is as expected

```
config: [3]
``` 
gives 

```json
{
  "config": [
    3
  ]
}
```

**Comment by laktak** [comment]
Note that for quoteless strings everything up to the next line is part of the string (see http://hjson.org/syntax.html#quoteless-strings)

The input

```
config: [max]
```

is equivalent to the following (with quotes):

```
config: ["max]"
```

Hjson can't parse that so it assumes you are defining a single quoteless string (`"config: [max]"`).

**Comment by mathiasrw** [comment]
Ok. Thanks for clear answer
