### ISSUE TITLE
We really need \n before ] ?

### ISSUE THREAD

**Issue by mathiasrw** [hjson/hjson#59]
On https://hjson.org/try.html I can do 

```
config:[
abc
]
```

and get the correct result, but if I do 

```

config:[
abc]
```

I get 

    Error: Syntax error, found trailing characters at line 2,1 >>>abc] ...

Is this intended?

**Comment by laktak** [comment]
Note that for quoteless strings everything up to the next line is part of the string (see http://hjson.org/syntax.html#quoteless-strings)

The input

```
config:[
abc]
```

is equivalent to the following (with quotes):

```
config:[
"abc]"
```

Hjson can't parse that and throws an error. The error was very misleading however so I published a fix, it now shows:

> Error: End of input while parsing an array (did you forget a closing ']'?)

**Comment by mathiasrw** [comment]
Makes sense then
