### ISSUE TITLE
Comma in the end

### ISSUE THREAD

**Issue by mathiasrw** [hjson/hjson#60]
> "Now I forgot the comma at the end."
> So you did. But Hjson does not mind as long as you put each value on a new line.

When not being consistent with the commas in an object like 

```hjson
{
  one: 1,
  two: 2
  three: 4 # oops
}
```

It gives the expected result 

```json
{
  "one": 1,
  "two": 2,
  "three": 4
}
````

but if I do the same with an array

```hjson
[
  one 1,
  two 2
  three 4
]
```

I get a trailing and unintended comma in my string

```json
[
  "one 1,",
  "two 2",
  "three 4"
]
```

**Comment by laktak** [comment]
Note that for quoteless strings everything up to the next line is part of the string (see http://hjson.org/syntax.html#quoteless-strings)

The input

```
[
  one 1,
  two 2
  three 4
]
```

is equivalent to the following (with quotes):

```
[
  "one 1,"
  "two 2"
  "three 4"
]
```

**Comment by mathiasrw** [comment]
Got it
