### ISSUE TITLE
! ABNF

### ISSUE THREAD

**Issue by mathiasrw** [hjson/hjson#61]
Looking at both

https://tools.ietf.org/html/rfc5234

and 

https://en.wikipedia.org/wiki/Augmented_Backus%E2%80%93Naur_Form

I see no syntax defined for the usage of `!`.

It looks like you use use it as a negation in for example https://github.com/hjson/hjson/blob/master/rfc/hjson.txt#L321

Is it correctly to assume that you use `!` to indicate that no instance of the following must occure?

If so, is it correct to assume that `!...` correspond to the notation of `*0(...)` ?

**Comment by laktak** [comment]
! is part of SABNF which is mentioned in a previous comment:

> 
>       ; SABNF: block-comment requies the use of the
>       ;        ! operator to allow * and / in the text
>       ;        while stopping at */
> 

You can find it here:

> 
>    [SABNF]    Thomas, L., "Superset Augmented Backus-Naur Form",
>               version 2.2.1, n.d., <https://github.com/ldthomas/apg-js2/blob/2fa136e00e5932d70ed1bd4786101c87afa8ca2e/SABNF.md>.
