### ISSUE TITLE
DOCs what's the spec on single quote key names?

### ISSUE THREAD

**Issue by lpgeiger** [hjson/hjson#65]
Crossposted here: https://github.com/hjson/hjson-js/issues/14

I'm guessing this may be an edge case, but I can't see any documentation on handling key names with single quotes vs double quotes.

In JS I would not expect that these two statements yield different results.
```
HJSON.parse('{ "a": 1}')
>{ a: 1 } //this is the expected response.

HJSON.parse("{ 'a': 1}")
> { '\'a\'': 1 } // unexpected
```

Even stranger to me is the behavior of single quotes with whitespace.
```
HJSON.parse('{ "a b": 1}')
>{ 'a b': 1 } // this is the expected response

HJSON.parse("{ 'a b': 1}")
>Error: Found whitespace in your key name (use quotes to include) at line 1,5 >>>{ 'a b': 1}
```

In the npm library 'relaxed-json' there is no difference between the single and double quote implementations.

**Comment by laktak** [comment]
Single quotes are not part of Hjson's syntax. You should either use double quotes or no quotes.

If you absolutely want single quotes you can [try this solution](https://github.com/hjson/hjson-js/issues/13) (not for keynames though).

**Comment by keyscores** [comment]
Ok, can you give me some background on this decision?
Will the HJSON syntax be modified in the foreseeable future?
It makes it a non-starter for my JS use case, which is converting JS objects to JSON.

**Comment by laktak** [comment]
Not sure I understand your question but Hjson is a superset of JSON which uses double quotes for strings.

If you are just converting JS objects this is probably not the right tool for the job.
