### ISSUE TITLE
ACE hjson Mode?

### ISSUE THREAD

**Issue by vote539** [hjson/hjson#66]
I noticed that you use a custom [hjson mode](https://github.com/hjson/hjson/blob/master/pages/try.html#L92) in the ACE editor on the hjson.org web site.  Any chance you can share the code and/or contribute it to upstream ACE? :smiley:

**Comment by laktak** [comment]
I made a [pull request to ACE](https://github.com/ajaxorg/ace/pull/3077) but I haven't been able to get anyone to approve it yet.

You should be able to install it from [here](https://github.com/laktak/ace/tree/hjson) though.

**Comment by laktak** [comment]
Hjson has been included in ACE for some time now.

**Comment by sffc** [comment]
Thanks!
