### ISSUE TITLE
Syntax has no end point

### ISSUE THREAD

**Issue by benkasminbullock** [hjson/hjson#67]
The syntax here:

https://hjson.org/syntax.html

has no end point. There has to be one valid final end point, like

    hjson: array 
         | object,

to define what a valid complete hjson output is.

As it is, there is no information about what a complete hjson syntax is, and the implication seems to be that the "object" type is the only one allowed. Since that contradicts JSON, I assume this is wrong, and the array type is also valid as the ultimate container.

**Comment by laktak** [comment]
The syntax diagrams are modeled after http://json.org. For a formal definition look at the RFC (at the bottom of the page). Does this help?

**Comment by benkasminbullock** [comment]
I looked at the syntax in the proposed RFC and found it's designed with arrays as values and objects without any curly braces. I suppose that's OK but it would be nice if the syntax page corresponded to the actual syntax.
