### ISSUE TITLE
Comments don't appear anywhere in the syntax

### ISSUE THREAD

**Issue by benkasminbullock** [hjson/hjson#68]
In the syntax, comments don't appear anywhere in the higher level items like objects and arrays, which doesn't make any sense at all. Are we supposed to strip comments out before parsing the input, or after? It's possible to have a string like

     {"string":"/* not a comment */"}

so stripping them out before would cause some errors. Usually the comments should be part of a whitespace, but the syntax also doesn't have anything about whitespace, either.

**Comment by laktak** [comment]
Whitespace and comments can be inserted between any pair of tokens.

They are defined in the RFC but I'll update the syntax page.
