### ISSUE TITLE
Omitting root braces not recommended?

### ISSUE THREAD

**Issue by qm3ster** [hjson/hjson#71]
As seen [in the documentation](https://hjson.org/syntax.html#root-braces-obsolete-), the automatic insertion of outermost brackets *should no longer be used*. Why is that?

**Comment by laktak** [comment]
Not having braces requires the parser to guess if this is either an object or a simple value. This is hard to implement and bug prone. 

When the input cannot be parsed the error messages can be unhelpful (because we don't know what the user tried to do) and in some cases it is possible that errors are hidden (for example when an invalid object can be parsed as an unquoted string).

Requiring braces also makes the syntax more consistent as they are also required for contained objects.

**Comment by StreetStrider** [comment]
The explanation seemes pretty reasonable. Such things always lead to a more complex and error prone parsers. However, for the record I must admit that I catch myself omitting top braces unintentionally many times and this feature is kinda of breakthrough and a time saver. It also allows to omit one level of tabs.

**Comment by qm3ster** [comment]
I would say that treating tab stop zero as the root of the object prevents errors in writing, which vastly outweighs being able to return for instance a primitive value (Who would do such a vile thing, anyway?)
However, returning an array might be useful sometimes.

**Comment by laktak** [comment]
Thanks for the input. I'll keep that in mind.

I don't plan on removing support for it though you may be required to explicitly request this feature in the future if you want it.

For why: Hjson has to work as a drop in replacment for JSON so it has to support primitives as well.

**Comment by qm3ster** [comment]
@StreetStrider I understand that there are perverted integration issues where the quickest way to do something is writing a file with a number literal. I have been in that situation as well.
But there's nothing stopping one from consuming that with JSON tools.
The benefit of loose+terse HJSON is in hand-writing e.g. configs, where `{}` or `[]` would be plenty for a null root.

I'd go so far as suggesting that just as
```
key: value
```
automatically emits an object
```
value
value
```
should automatically emit an array

completely empty files can continue to emit `{}` as they do now, or error out.
an empty array can be emitted with a literal `[]`

**Comment by pchampin** [comment]
I **really** think that omitting curly braces for the root object is a valuable feature for HJson, and should **not** be discouraged. The fact that a simple "record" can be written:
```
hello: world
foo: bar
answer: 42
```
is great for many people for whom JSON is already too complicated. They only need brackets (curly or square) when they need to embed complex values in the attributes of the root object, which is arguably already an advanced use-case.
