### ISSUE TITLE
Can't parse compact notation with several keys on the same line

### ISSUE THREAD

**Issue by Offirmo** [hjson/hjson#72]
I discovered HJSON recently and was very excited.

However, it seems the parser can't understand lines like the 3 last of this:
```
[
	{
		date: 12/12/2004
		amount: 12.99
		currency: EUR
	},
	{ date: 12/10/2004,   amount:    12.99, currency: EUR },
	{ date: 13/10/2004,   amount:   112.99, currency: EUR },
	{ date: 12/10/2004,   amount:  -812.99, currency: EUR },
]
```

That's too bad, this column-aligned notation is very convenient.

I tried enclosing values in `'` quotes, with no success.

Can't we have commas having priority ?

**Comment by Offirmo** [comment]
In the meantime I found https://github.com/timjansen/hanson

It's less relaxed, but allows this kind of construct.

**Comment by laktak** [comment]
That's correct. Quoteless strings must be put onto their own line.

**Comment by Offirmo** [comment]
@laktak are you implying that quoted strings would allow one-line notation ? I couldn't make it work...

**Comment by laktak** [comment]
I'm on mobile so I don't have a sample for you. Quotes require " (not ').
