### ISSUE TITLE
C++

### ISSUE THREAD

**Issue by trobro** [hjson/hjson#75]
I really like the Hjson format for configuration files, so I've created a C++ implementation:

https://github.com/trobro/hjson-cpp

I've included the test cases from hjson-go, and added a test file strings3_test.hjson to avoid issue #8 from hjson-go.

Would be fun to have the C++ implementation included in the official project.

**Comment by laktak** [comment]
Hey that's great - thanks for your work! I've sent you an invite to hjson.

After you have joined you should be able to move the repo to hjson/hjson-cpp and I'll add the links on the site.

**Comment by trobro** [comment]
Thanks, will do!

**Comment by trobro** [comment]
I got the error message "You don’t have the permission to create repositories on hjson".

**Comment by laktak** [comment]
In that case please transfer the repo to me and I'll add it.

**Comment by trobro** [comment]
Ok I've created a transfer request.

**Comment by laktak** [comment]
Thanks! The repo is now here: https://github.com/hjson/hjson-cpp and I set you up as admin.

I'll add links for hjson-cpp to hjson.org soon.

**Comment by laktak** [comment]
The links are now live as well. Thanks again!

**Comment by trobro** [comment]
Nice!
