### ISSUE TITLE
windows 64 bit binary appears to be malware infected

### ISSUE THREAD

**Issue by JohnLelii-CMCST** [hjson/hjson#76]
![hjson](https://user-images.githubusercontent.com/23384463/30709813-7e025c42-9ed1-11e7-94ab-5abcb5f8a2ec.jpg)

see attached image

**Comment by JohnLelii-CMCST** [comment]
https://github.com/hjson/hjson-go/releases/download/v3.0.0/windows_amd64.zip

**Comment by laktak** [comment]
The releases are built on a Linux machine run by [travis-ci](http://travis-ci.org/hjson/hjson-go). If they had malware on their servers a lot of go binaries would be affected.

Reading on the [Symantec site](https://www.symantec.com/security_response/writeup.jsp?docid=2010-051308-1854-99) this sounds a lot like FUD:

> WS.Reputation.1 is a detection for files that have a low reputation score based on analyzing data from Symantec’s community of users and therefore are likely to be security risks. Detections of this type are based on Symantec’s reputation-based security technology. Because this detection is based on a reputation score, it does not represent a specific class of threat like adware or spyware, but instead applies to all threat categories.

> The reputation-based system uses "the wisdom of crowds" (Symantec’s tens of millions of end users) connected to cloud-based intelligence to compute a reputation score for an application, and in the process identify malicious software in an entirely new way beyond traditional signatures and behavior-based detection techniques.

Could you report this false positive to symantec? Their form is here: https://submit.symantec.com/false_positive

**Comment by JohnLelii-CMCST** [comment]
understood.  closing ticket.
