### ISSUE TITLE
[Feature request] Hjson validator

### ISSUE THREAD

**Issue by Kristinita** [hjson/hjson#78]
### 1. Request

I don't find Hjson validator. Possibly, it doesn't exist.

### 2. Argumentation

I want to use hjson validation in continuous integration services as [**Travis CI**](https://travis-ci.org/).

Expected behavior:

**If** hjson files is valid:

    build passed

**else**:

    build failed

### 3. Not helped

For example, I try [**npm-hjson**](https://www.npmjs.com/package/hjson):

my non-valid file `KatePalette.hjson` (missing brace):

```hjson
{
  // Comment
  /*
  Multiline comment
   */
  human:   Hjson
  machine: JSON

```

[**TravisCI build**](https://travis-ci.org/Kristinita/SashaHjsonValidate/builds/331774398):

```javascript
Error: End of input while parsing an object (missing '}') at line 8,1 >>> …


The command "hjson "KatePalette.hjson"" exited with 0.
```

TravisCI show an error, but build passed.

Thanks.

**Comment by laktak** [comment]
fixed by 3.1.1.
