### ISSUE TITLE
Advantages over YAML?

### ISSUE THREAD

**Issue by mk-pmb** [hjson/hjson#8]
Hi!
I don't quite get it. One major benefit of JSON is that you can drop it into JS literally if you really really trust the author of your config or have verified that it really is striclty JSON. As far as I see, that benefit is gone with HJSON, not even attempting to use the same one-line comment syntax.
If you want human friendly configs, what benefit would HJSON have over [YAML](http://en.wikipedia.org/wiki/YAML#Sample_document)?

Yours, mk

**Comment by MattiSG** [comment]
Absolute +1 here. I actually believed this to be a joke where every time you remove a JSON constraint, and you'd end up removing the enclosing brackets and say “hey, that's called YAML and it's been around for years!”.

If your conclusion is “keep it for internal setup” (which you definitely should, as it's not interoperable), just use YAML. It's more “human” (I can even get non-programmers to use it), and libraries for it have been battle-tested.

**Comment by liukun** [comment]
I personally use Hjson to remove comments and possible typos from JSON files written by non-programmer. It works great! Thanks to the developer(s)!

The most important advantage: YAML requires more formatting than JSON, Hjson requires less.
And a quote from [TOML](https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.4.0.md#but-why):
> Because we need a decent human-readable format that unambiguously maps to a hash table and the YAML spec is like 80 pages long and gives me rage. No, JSON doesn't count. You know why.

**Comment by MattiSG** [comment]
> the YAML spec is like 80 pages
> 
It turns out that grammars are a pretty complex thing to get unambiguously right when you want to support formatted data structures without control characters  :)
