### ISSUE TITLE
Cross-collaboration with JSON5

### ISSUE THREAD

**Issue by DonaldTsang** [hjson/hjson#87]
It would be a good idea to collaborate with other JSON supersets like https://github.com/json5/json5
Some ideas:
1. discuss the difference between HJSON and JSON5
2. creating a cross-compatible intermediates format between the two
3. (possibly) standardize a new superset through communication and documentation

See https://github.com/json5/json5/issues/190

**Comment by dqsully** [comment]
I think this would be pretty cool. It would have to make some compromises between the different ideals of JSON5 and Hjson, but one unified, backwards-compatible format would make it easier to maintain and easier for users to choose. I'll have to think on it for a bit. In fact I'll see if I can prototype a spec and implementation in some of my free time

**Comment by DonaldTsang** [comment]
It would be great to have you on the issue as well

**Comment by dqsully** [comment]
Summarizing from the JSON5 discussion:

Combining the two languages is pretty-much impossible unfortunately. JSON5 and Hjson have two different directions, albeit with the same purpose and goal. JSON5 and its variants are strictly tied to the ECMAScript spec, but Hjson is more freeform, for lack of a better phrase. However, I believe we can still collaborate on a parser and its features, so I've started working on such a parser.

**Comment by PSVortex** [comment]
@dqsully I added some thougths and critisism to https://github.com/json5/json5/issues/190#issuecomment-544475103 I want to encourage you to continue you work and stop worring that some other peojects have different goals. The HJSON is not perfect but for me it's cleary the one alternative to JSON which is worth using.
