### ISSUE TITLE
Lua

### ISSUE THREAD

**Issue by cryi** [hjson/hjson#88]
Hi, I plan to use hjson for configuration in Lua scripts and so I ported [hjson-py](https://github.com/hjson/hjson-py) to Lua with some adjustments from [json.lua](https://github.com/rxi/json.lua).

You can find repository here: [hjson-lua](https://github.com/cryi/hjson-lua)

Test suite is ported from hjson-js and all 87 test passes successfully. 

I would like to include Lua implementation in the official project. Is it possible ?

**Comment by dqsully** [comment]
I'm totally open to this, any thoughts @laktak?

Also, what would we need to do to add this project to LuaRocks? I'm not very familiar with the Lua ecosystem.

**Comment by cryi** [comment]
Honestly, I'm not very familiar with the Lua ecosystem either. I use a custom Lua interpreter, linked with some essential libraries and with minimal size. I plan to release it as well.

But based on what I saw, it shouldn't be an issue to provide a LuaRocks package, since hjson-lua is pure Lua code.It seems to consist of creating a LuaRocks specs file and then publishing the whole repository to LuaRocks. It sounds like a relatively simple process.

I may look into that some time later... I'm busy with other stuff for now.

**Comment by cryi** [comment]
Hi, I haven't had time to look into LuaRocks yet and might not be able to for a while. So any contribution would be appreciated :)

**Comment by cryi** [comment]
Hi, hjson-lua is now available through [luarocks](https://luarocks.org/modules/cryi/hjson-lua/0.1.2-2). @dqsully

**Comment by cryi** [comment]
Hey @laktak @dqsully can we list lua implementation on hjson website?

**Comment by trobro** [comment]
Nice work @cryi! I have added badges and links on the Hjson website. It would be nice to also move hjson-lua into the Hjson organization, but only @laktak can do that.

**Comment by laktak** [comment]
Hi sorry for the late response.

@cryi do you want to move hjson-lua to the hjson org and be added as a member?

@trobro @dqsully do you agree?

**Comment by cryi** [comment]
Yes if it works for you we can do it 🙂

**Comment by laktak** [comment]
@cryi I sent you an invite. If I remember correctly you need to transfer the repository to me or @dqsully and we will then add it to hjson.

**Comment by cryi** [comment]
@laktak @dqsully  request for transfer sent.

**Comment by dqsully** [comment]
I don't see a request on my end, so I'm guessing you sent it to @laktak.

**Comment by cryi** [comment]
@dqsully 
![image](https://user-images.githubusercontent.com/36897290/150219196-50a2ad72-b866-4001-9216-b51bc6030cb5.png)

**Comment by laktak** [comment]
@dqsully you need to check your mail - afaik it's not visible on the website.

**Comment by dqsully** [comment]
Right. Also for some reason that email went to spam, but I found it now

**Comment by dqsully** [comment]
https://github.com/hjson/hjson-lua
