### ISSUE TITLE
Literal Tabs in Quoted Strings

### ISSUE THREAD

**Issue by robshostak** [hjson/hjson#89]
Are literal tabs (i.e, the character 0x9) permitted in quoted strings in hjson?  I don't believe ordinary json syntax permits these, but the hjson syntax diagram labeled "JSON-string" does not seem to preclude them, as it appears to allow any character other than starting quote and \ to be contained within a quoted string.  

I'm using hjson-java, and have found that readFile() throws an error exception "Expected valid string character"  (at least in a couple of cases I tried) when a quoted string used as the value of a member of an object contains a literal tab.    Thanks for the help.

**Comment by sffc** [comment]
I don't know why a 0x9 character would be disallowed in this context.  Do you get the same error in other languages?  Do you get it if you parse the Hjson from a string rather than from a file?

**Comment by robshostak** [comment]
Hi, Shane –

 

Thanks for your quick response.   Interestingly, if I parse a String, it works:

 

String    s             =            “{a: \”   \”}”;

JsonValue  jv     =            JsonValue.readHJson(s);

 

In the example above, there is a tab character (0x9) between the two escaped quotes.   No exception occurs, and the return value jv is correct.

 

However, if I have an ascii file named test.hjson containing the single line:

 

{a: \”     \”}

 

where once again, there is a single tab character between the two escaped quotes, and execute

 

Reader r             =            new FileReader(test.hjson);

JsonValue jv      =            JsonValue.readHjson(r) ;

 

then an exception is thrown with message “Expected valid string character at 1:5”.

 

So the problem does seem to have something to do with the file i/o.   Wonder if you are set up with Java so you can try the same thing.   I’ve only tried this with Java (and it would be a pain for me to use one of the other languages).  What I would do if I had a little more time would be to create a String from the file using the FileReader and check that this looks okay.

 

Thanks again -

Rob

**Comment by sffc** [comment]
Ok, great, so it sounds like a Java bug then. Please file a bug on that repo. This is the repo for Hjson in general, not a specific implementation of it.

**Comment by robshostak** [comment]
Will do – thanks again, Shane.
