### ISSUE TITLE
Comments?

### ISSUE THREAD

**Issue by jprichardson** [hjson/hjson#9]
Why not use `//` instead of `#`? It seems to me that anyone coming from JavaScript would have this expectation.

**Comment by laktak** [comment]
`//` comments are now supported as well as `#` comments. This makes it possible to use Hjson as a replacement for config files that already use JSON + `//` comments.

**Comment by matthew-dean** [comment]
Say I have this structure: 
```
prop: {
  foo: #bar
}
```
If I want the value of "foo" to be "#bar", how would I escape comments. Is there any way to do it other than enclosing everything in quotes?
