### ISSUE TITLE
Redirect http to https

### ISSUE THREAD

**Issue by dzikoysk** [hjson/hjson#91]
Support automatic HTTPS rewrites due to:

![obraz](https://user-images.githubusercontent.com/4235722/66164449-feda8d80-e632-11e9-9b65-b81f59f7ac4f.png)

Also update link in the organization and the repository

**Comment by dqsully** [comment]
@laktak It looks like GitHub pages can do this for us, we just need to change the A records: https://help.github.com/en/articles/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain

**Comment by laktak** [comment]
Redirection is now active.

**Comment by dzikoysk** [comment]
Also update link here 

![obraz](https://user-images.githubusercontent.com/4235722/68143202-42c1fa80-ff31-11e9-9d0c-e77c0e1926de.png)
👍
