### ISSUE TITLE
hjson-kotlin

### ISSUE THREAD

**Issue by dhakehurst** [hjson/hjson#95]
Hi,
I want to use hjson from kotlin.
I know that there is a hjson-java and a hjson-js version.

But I want to use a kotlin-common implementation.
I will implement this.
Would you be interested in my adding it to this github repo?
i.e. an hjson-kotlin (that is suitable for kotlin multilatform use)

**Comment by sffc** [comment]
I would support this.  How about if you start by building this in a repo in your own account, and then we can look to transfer the repo into the hjson org once it is ready.

**Comment by trobro** [comment]
@dhakehurst I see you created an implementation (dhakehurst/net.akehurst.kotlin.hjson), does it pass all test cases? Would you like me to add a link to it on https://hjson.github.io/download.html?

**Comment by dhakehurst** [comment]
sure you are welcome to do so.

no it does not pass all tests.

**Comment by trobro** [comment]
Thanks, I have added it in the list of partial implementations.
