### ISSUE TITLE
Hjson to Json - Yeah that would be great!

### ISSUE THREAD

**Issue by bigBxr** [hjson/hjson#97]
It would be great if there were a compiler that converts Hjson to Json, something similar to how SCSS compiles to CSS.

**Comment by sffc** [comment]
You can do this in your programming language of choice by using the Hjson library to load Hjson, then serializing the data using your favorite Json stringifier.

**Comment by trobro** [comment]
A lot of the Hjson implementations are able to do this, for example hjson-cpp has the function MarshalJson(). So you would first unmarshal the Hjson string, then marshal the result to a Json string.
