### ISSUE TITLE
Definition of whitespace?

### ISSUE THREAD

**Issue by schveiguy** [hjson/hjson#99]
json.org defines whitespace as space, linefeed, carriage return, or horizontal tab. hjson does not define whitespace in the syntax document. I would hope that it is the same, as unicode spaces can be complex...

Can you confirm this is the case?

**Comment by dqsully** [comment]
Yes this is correct. You can find the full syntax specification in the RFC: https://hjson.org/rfc.html#rfc.section.2

**Comment by schveiguy** [comment]
OK, thanks, I didn't know there was an alternative spec. That still leaves this document without a definition of whitespace: https://hjson.github.io/syntax.html

I'll see if I can put together a PR.
